### ISSUE TITLE
Need regress tests

### ISSUE THREAD

**Issue by dzavalishin** [dzavalishin/mqtt_udp#36]
Run differrent publish scripts and check for data to come. Run different listen scripts, send data and check reception.

## Fixed/implemented in:

- [ ] Pyhon implementation
- [ ] Java implementation
- [ ] C implementation/Unix
- [ ] Lua implementation

CodeSys and Embedded C code is impossible to test this way, is it?

- [x] Added to Travis CI

## Subtasks

- [x] write regress_send/regress_recv for all impls
- [ ] write suit to run all the recv programs redirected to files, then run sequentally all senders > to files too, then check all files to be correct

## Ref

https://stackoverflow.com/questions/6998955/running-external-program-using-pipes-and-passing-arguments-in-python

https://stackoverflow.com/questions/51994517/python-run-bash-script-with-flags-and-pipes

https://python-scripts.com/subprocess

**Comment by dzavalishin** [comment]
https://stackoverflow.com/questions/6998955/running-external-program-using-pipes-and-passing-arguments-in-python

https://stackoverflow.com/questions/51994517/python-run-bash-script-with-flags-and-pipes

https://python-scripts.com/subprocess

**Comment by dzavalishin** [comment]
## Travis refs

https://docs.travis-ci.com/user/build-stages/
https://habr.com/post/329264/
https://habr.com/company/southbridge/blog/329262/
https://habr.com/company/true_engineering/blog/323760/

**Comment by dzavalishin** [comment]
Current status: Travis CI runs tests for Java, C and Python3. 

Need: 

* run Lua tests
* add tests for sending / listening
* integral test all with all
